services:
  database:
    build:
      dockerfile: Database/Dockerfile
    environment:
      POSTGRES_USER: airflow
      POSTGRES_PASSWORD: airflow
      POSTGRES_DB: airflow
    ports:
      - 6432:5432
    volumes:
      - ${AIRFLOW_PROJ_DIR:-.}/Database:/docker-entrypoint-initdb.d
    healthcheck:
      test: ["CMD", "pg_isready", "-U", "airflow"]
      interval: 10s
      retries: 5
      start_period: 5s
    restart: always

#  airflow_db:
#    build:
#      dockerfile: Airflow/Dockerfile
#    environment:
#      POSTGRES_USER: airflow
#      POSTGRES_PASSWORD: airflow
#      POSTGRES_DB: airflow
#    ports:
#      - 6666:5432
#    volumes:
#      - ${AIRFLOW_PROJ_DIR:-.}/Airflow/postgres_data_airflow:/global
#    healthcheck:
#      test: [ "CMD", "pg_isready", "-U", "airflow" ]
#      interval: 10s
#      retries: 5
#      start_period: 5s
#    restart: always